version: '3'

services:
  blamer:
    image: blamer
    container_name: blamer_container
    restart: always
    environment:
      - TG_TOKEN = ${{ secrets.TG_TOKEN }}
      - GITHUB_TOKEN = ${{ secrets.GH_TOKEN }}

