name: CD
run-name: CD pipline on main branch
on: 
  push:
    branches:
      - 'main'
      - 'deploy'


defaults:
  run:
    shell: bash


jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Get updates on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "blamer" ]; then 
                git clone "${{ github.repository }}" "blamer" 
            fi
            cd "blamer"
            git pull origin main
            docker-compose down
            docker rm blamer_container
            docker rmi blamer
            docker build -t "blamer" .
            docker-compose up -d

