name: CD
run-name: CD pipline on main branch
on: 
  push:
    branches:
      - 'main'
      - 'deploy'
      - 'db-setup'


defaults:
  run:
    shell: bash


jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo updates
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "blamer" ]; then 
            git clone "https://github.com/${{ github.repository}}.git" "blamer" 
            fi
            cd blamer
            git pull origin ${{ github.ref }}
            git checkout $GITHUB_REF

      - name: Update envs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd blamer
            rm .env
            touch .env

            echo "TG_TOKEN=" ${{ secrets.TG_TOKEN }} >> .env
            echo "GH_TOKEN=" ${{ secrets.GH_TOKEN }} >> .env
            echo "DB_NAME=" ${{ vars.DB_NAME}} >> .env
            echo "DB_USERNAME=" ${{ vars.DB_USERNAME }} >> .env
            echo "DB_PASSWORD=" ${{ vars.DB_PASSWORD }} >> .env

            echo "DB_HOST=blamer-db" >> .env
            echo "DB_PORT=5432" >> .env

      - name: Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd blamer
            make
