name: CD
run-name: CD pipline on main branch
on: 
  push:
    branches:
      - 'main'
      - 'deploy'


defaults:
  run:
    shell: bash


jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Get get updates
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "blamer" ]; then 
            git clone "https://github.com/${{ github.repository}}.git" "blamer" 
            fi
            cd blamer
            git pull origin ${{ github.ref }}
            git checkout ${{ github.ref }} 

      - name: Update secrets
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd blamer
            rm secrets.env
            touch secrets.env
            echo "TG_TOKEN=" ${{ secrets.TG_TOKEN }} >> secrets.env
            echo "GH_TOKEN=" ${{ secrets.GH_TOKEN }} >> secrets.env

      - name: Down compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd blamer
            docker-compose down
            docker rm blamer_container
            docker rmi blamer
            docker build -t "blamer" .
            docker-compose up -d

      - name: Remove old image and container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd blamer
            docker rm blamer_container
            docker rmi blamer

      - name: Build new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd blamer
            docker build -t "blamer" .

      - name: Run compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd blamer
            docker-compose up -d

